from django.urls import path

from .views import (
    AdminCustomerDetailView,
    AdminCustomerListView,
    StockBillUploadView,
    StockBillUploadListView,
    StockBillUploadDetailView,
    AdminInventoryCategoryDetailView,
    AdminInventoryCategoryListCreateView,
    AdminInventoryBatchDetailView,
    AdminInventoryBatchListCreateView,
    AdminInventoryCompanyDetailView,
    AdminInventoryCompanyListCreateView,
    AdminInventoryProductDetailView,
    AdminInventoryProductListCreateView,
    AdminSaltDetailView,
    AdminSaltListCreateView,
    AdminOrderDetailView,
    AdminOrderBillPrintView,
    AdminOrderBillView,
    AdminOrderBillDownloadView,
    AdminOrderListCreateView,
    AdminOrderReceiptDownloadView,
    AdminOrderReceiptPrintView,
    AdminOrderReceiptView,
    AdminOrderStatusUpdateView,
    AdminPrescriptionDetailView,
    AdminPrescriptionListView,
)

urlpatterns = [
    path("customers/", AdminCustomerListView.as_view()),
    path("customers/<int:pk>/", AdminCustomerDetailView.as_view()),
    path("prescriptions/", AdminPrescriptionListView.as_view()),
    path("prescriptions/<int:pk>/", AdminPrescriptionDetailView.as_view()),
    path("orders/", AdminOrderListCreateView.as_view()),
    path("orders/<int:pk>/", AdminOrderDetailView.as_view()),
    path("orders/<int:pk>/status/", AdminOrderStatusUpdateView.as_view()),
    path("orders/<int:pk>/bill/", AdminOrderBillView.as_view()),
    path("orders/<int:pk>/bill/print/", AdminOrderBillPrintView.as_view()),
    path("orders/<int:pk>/bill/download/", AdminOrderBillDownloadView.as_view()),
    path("orders/<int:pk>/receipt/", AdminOrderReceiptView.as_view()),
    path("orders/<int:pk>/receipt/print/", AdminOrderReceiptPrintView.as_view()),
    path("orders/<int:pk>/receipt/download/", AdminOrderReceiptDownloadView.as_view()),
    path("inventory/products/", AdminInventoryProductListCreateView.as_view()),
    path("inventory/products/<int:pk>/", AdminInventoryProductDetailView.as_view()),
    path("inventory/batches/", AdminInventoryBatchListCreateView.as_view()),
    path("inventory/batches/<int:pk>/", AdminInventoryBatchDetailView.as_view()),
    path("inventory/salts/", AdminSaltListCreateView.as_view()),
    path("inventory/salts/<int:pk>/", AdminSaltDetailView.as_view()),
    path("inventory/categories/", AdminInventoryCategoryListCreateView.as_view()),
    path("inventory/categories/<int:pk>/", AdminInventoryCategoryDetailView.as_view()),
    path("inventory/companies/", AdminInventoryCompanyListCreateView.as_view()),
    path("inventory/companies/<int:pk>/", AdminInventoryCompanyDetailView.as_view()),
    path("inventory/stock-bill/upload/", StockBillUploadView.as_view()),
    path("inventory/stock-bill/uploads/", StockBillUploadListView.as_view()),
    path("inventory/stock-bill/uploads/<int:pk>/", StockBillUploadDetailView.as_view()),
]
