# Generated by Django 6.0.2 on 2026-04-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('batch_number', models.CharField(blank=True, default='', max_length=80)),
                ('company_name', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('ingredients_list', models.JSONField(blank=True, default=list)),
                ('concerns_list', models.JSONField(blank=True, default=list)),
                ('prevents_list', models.JSONField(blank=True, default=list)),
                ('needs_list', models.JSONField(blank=True, default=list)),
                ('product_details', models.TextField(blank=True)),
                ('in_depth_information', models.TextField(blank=True)),
                ('allergic_warning', models.TextField(blank=True)),
                ('otc_information', models.TextField(blank=True)),
                ('habit_forming_information', models.TextField(blank=True)),
                ('diet_lifestyle_advice', models.TextField(blank=True)),
                ('consume_type', models.CharField(default='oral', max_length=30)),
                ('safety_advice', models.JSONField(blank=True, default=dict)),
                ('faqs', models.JSONField(blank=True, default=dict)),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=100)),
                ('strength', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.CharField(blank=True, default='', max_length=100)),
                ('prescription_required', models.BooleanField(default=False)),
                ('uses', models.TextField(blank=True)),
                ('directions_for_use', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('strip', 'Strip'), ('bottle', 'Bottle'), ('pack', 'Pack'), ('tube', 'Tube'), ('jar', 'Jar'), ('box', 'Box'), ('piece', 'Piece'), ('ml', 'ml'), ('gm', 'gm')], default='piece', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineSalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_salts', to='catalog.product')),
                ('salt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salt_medicines', to='catalog.salt')),
            ],
            options={
                'unique_together': {('medicine', 'salt')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='salts',
            field=models.ManyToManyField(blank=True, related_name='medicines', through='catalog.MedicineSalt', to='catalog.salt'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=80)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=150)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('location_code', models.CharField(blank=True, default='', max_length=50)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='catalog.product')),
            ],
            options={
                'ordering': ['expiry_date', 'id'],
                'unique_together': {('medicine', 'batch_number', 'location_code')},
            },
        ),
    ]
